### ISSUE TITLE
Doesn't work on Chrome

### ISSUE THREAD

**Issue by kirkbushell** [phuctm97/tailwindcss-autofill#36]
I followed all your steps, and although I found it working on Firefox and Safari, this doesn't seem to work on Chrome.

**Comment by phuctm97** [comment]
Please read the usage section. 

> This plugin is often used with the [tailwindcss-shadow-fill](https://github.com/phuctm97/tailwindcss-shadow-fill) and [tailwindcss-text-fill](https://github.com/phuctm97/tailwindcss-text-fill) because background-color and color won't work.
