### ISSUE TITLE
chrome autofill-selected has a quirk and need different properties set to make this work

### ISSUE THREAD

**Issue by aikomastboom** [phuctm97/tailwindcss-autofill#6]
Hey.. this plugin is a great idea.. however on Chrome it doesn't work (yet) for `-webkit-autofill-selected`
please check out: https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

the trick is in also setting:
```css
    -webkit-box-shadow: 0 0 0 1000px green inset !important;
    -webkit-text-fill-color: white !important;
```

also note: from that StackOverflow, I understand there is also: `:-webkit-autofill:active`

**Comment by bymayo** [comment]
I also have similar issues with Chrome, but mine is being overwritten by `input:-internal-autofill-selected` selector:

```
input:-internal-autofill-selected {
    appearance: menulist-button;
    background-image: none !important;
    background-color: -internal-light-dark(rgb(232, 240, 254), rgba(70, 90, 126, 0.4)) !important;
    color: -internal-light-dark(black, white) !important;
}
```

**Comment by phuctm97** [comment]
Just updated the docs. You'll have to use `tailwindcss-shadow-fill` and `tailwindcss-text-fill` because `background-color` and `color` won't with autofill.
