### ISSUE TITLE
Update to use tailwind v3?

### ISSUE THREAD

**Issue by danimalweb** [phuctm97/tailwindcss-autofill#9]
`npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^2.0.2" from tailwindcss-autofill@0.1.0
npm ERR! node_modules/tailwindcss-autofill
npm ERR!   tailwindcss-autofill@"^0.1.0" from the root project`

Would be ideal if the peerDep could be updated to use the latest version of Tailwind.

**Comment by phuctm97** [comment]
Tks for reporting @danimalweb, a PR from you would be awesome!

**Comment by danimalweb** [comment]
@phuctm97 [PR](https://github.com/phuctm97/tailwindcss-autofill/pull/10) opened.

**Comment by phuctm97** [comment]
Thanks for the issue and PR @danimalweb.
Fixed!
